export type ProjectData = {
  title: string;
  description: string;
  tags: string[];
  imageLight: string;
  imageDark: string;
  link: string;
  github: string;
  demo: string;
  order: number;
  hidden?: boolean;
};

export const STATIC_PROJECTS: ProjectData[] = [
  {
    title: "dTunes",
    description: "A full-stack music platform for local artists to upload, share, and monetize their music.",
    tags: ["Next.js", "Firebase", "Stripe", "Tailwind CSS"],
    imageLight: "/images/dtunes.png",
    imageDark: "/images/dtunes.png",
    link: "/projects/dtunes",
    github: "https://github.com/RebornPixels/dTunes",
    demo: "https://dtunes.vercel.app",
    order: 0,
  },
  {
    title: "Dzaleka Online",
    description: "Community social platform connecting refugees through stories, media sharing, and real-time chat.",
    tags: ["Next.js", "Firestore", "Real-time", "Social"],
    imageLight: "/images/dcitylight.png",
    imageDark: "/images/dcitydark.png",
    link: "/projects/dzaleka-online",
    github: "https://github.com/RebReborn/dzalekaonline",
    demo: "https://dzalekaonlineh.web.app/",
    order: 1,
  },
  {
    title: "Reborn Pixels",
    description: "Creative portfolio showcasing photography and videography work with Cloudinary integration.",
    tags: ["Next.js", "Cloudinary", "Photography", "Admin"],
    imageLight: "/images/reborn.png",
    imageDark: "/images/rebornGold.png",
    link: "/projects/reborn-pixels",
    github: "https://github.com/RebornPixels/portfolio",
    demo: "https://reborn-pixels-production.web.app",
    order: 2,
  },
  {
    title: "Windows of Hope",
    description: "Non-profit platform featuring donation processing, volunteer coordination, and impact stories.",
    tags: ["Next.js", "MongoDB", "Non-profit", "Stripe"],
    imageLight: "/images/wohopelight.png",
    imageDark: "/images/wohopedark.png",
    link: "/projects/windows-of-hope",
    github: "https://github.com/RebReborn/windows-of-hope",
    demo: "https://windowsofhope.vercel.app",
    order: 3,
  },
  {
    title: "Telegram Media Downloader",
    description: "Browser-based tool to securely download media from Telegram chats and channels.",
    tags: ["React", "Telegram API", "GramJS", "Media Downloader"],
    imageLight: "/images/tmdownloader.png",
    imageDark: "/images/tmdownloader.png",
    link: "/projects/tmdownloader",
    github: "https://github.com/rebreborn/telegram-media-downloader",
    demo: "https://tmdownloader.vercel.app/",
    order: 4,
  },
  {
    title: "LoopHire",
    description: "A social job referral platform that connects job seekers with professionals willing to refer them.",
    tags: ["React", "Firebase", "Job Board", "Referral Platform"],
    imageLight: "/images/loophire.png",
    imageDark: "/images/loophire.png",
    link: "/projects/loophire",
    github: "https://github.com/rebreborn/referral",
    demo: "https://loophire.netlify.app/",
    order: 5,
  },
  {
    title: "Instagram Non-Followers Checker",
    description: "A browser-based tool that helps Instagram users identify who isn't following them back.",
    tags: ["Instagram", "Non-Followers", "Browser Tool", "Social Media"],
    imageLight: "/images/instagram.png",
    imageDark: "/images/instagram.png",
    link: "/projects/instagram-non-followers-checker",
    github: "",
    demo: "https://instagram-non-followers.vercel.app/",
    order: 6,
  },
  {
    title: "Malawi Maketi",
    description: "An e-commerce marketplace tailored for Malawi, featuring local mobile money (Airtel API) and vendor stores.",
    tags: ["React", "Firebase", "Mobile Money", "E-Commerce"],
    imageLight: "/images/maketi_light.png",
    imageDark: "/images/maketi_dark.png",
    link: "/projects/maketi",
    github: "https://github.com/rebreborn/malawi-maketi",
    demo: "https://maketi.vercel.app",
    order: 7,
  },
  {
    title: "FtBuddy",
    description: "Voice-powered AI fitness assistant with workout tracking, nutrition analysis, and real-time coaching.",
    tags: ["React Native", "Firebase", "Voice AI", "Fitness"],
    imageLight: "/images/ftbuddy_light.png",
    imageDark: "/images/ftbuddy_dark.png",
    link: "/projects/ftbuddy",
    github: "https://github.com/rebreborn/",
    demo: "https://ftbuddy.netlify.app/",
    order: 8,
  },
  {
    title: "Kibembe Language App",
    description: "A community-driven language learning app for Kibembe featuring audio/image contributions and AI validation.",
    tags: ["React", "Firebase", "Language Learning", "AI"],
    imageLight: "/images/kibembe_light.png",
    imageDark: "/images/kibembe_dark.png",
    link: "/projects/kibembe",
    github: "https://github.com/rebreborn/",
    demo: "https://kibembe.com/",
    order: 9,
  },
  {
    title: "Swahili Number Converter",
    description: "A simple tool that converts numeric values into written Swahili words.",
    tags: ["React", "Swahili", "Language Tools", "Education"],
    imageLight: "/images/swahili2words.png",
    imageDark: "/images/swahili2words_2.png",
    link: "/projects/swahili-number-converter",
    github: "https://github.com/RebReborn/swahili2words",
    demo: "",
    order: 10,
  },
  {
    title: "Lunax Decor",
    description: "An event and wedding decor service offering elegant setups, floral arrangements, and personalized design.",
    tags: ["Business", "Event Decor", "Weddings", "Creative Services"],
    imageLight: "/images/lunax_light.png",
    imageDark: "/images/lunax_dark.png",
    link: "/projects/lunaxdecor",
    github: "",
    demo: "https://lunaxdecor.com/",
    order: 11,
  },
  {
    title: "MoodShare",
    description: "A social media app for sharing moods, moments, and expressions.",
    tags: ["React Native", "Firebase", "Social Media", "Mobile App"],
    imageLight: "/images/moodshare_light.png",
    imageDark: "/images/moodshare_dark.png",
    link: "/projects/moodshare",
    github: "https://github.com/rebreborn/",
    demo: "https://moodshare.netlify.app/",
    order: 12,
  },
  {
    title: "Reborn Pixels (Photography)",
    description: "A creative photography and videography portfolio showcasing events, weddings, portraits, and brand visuals.",
    tags: ["Photography", "Videography", "Portfolio", "Creative Services"],
    imageLight: "/images/rebornpixels.png",
    imageDark: "/images/rebornpixels.png",
    link: "/projects/reborn-netflix",
    github: "",
    demo: "https://rebornpixels.netlify.app/",
    order: 13,
  },
  {
    title: "DoPeVest",
    description: "A community-driven investment platform where 100 members pool resources to generate passive income.",
    tags: ["React", "Firebase", "Community Investment", "Netlify"],
    imageLight: "/images/dopevest_light.png",
    imageDark: "/images/dopevest_dark.png",
    link: "/projects/dopevest",
    github: "",
    demo: "https://dopevest.netlify.app/",
    order: 14,
  },
];
